name: Java CI with Gradle and Docker

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

defaults:
  run:
    using: self-hosted
    runner-label: sarvani

jobs:
  build-java:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

  build-docker:
    runs-on: self-hosted
    needs: build-java
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: sarvanigudavalli/githubactionsdemo
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
